# Generated by Django 3.1.12 on 2021-06-24 15:23

from django.db import migrations, models
import poolink_backend.apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', poolink_backend.apps.users.models.UserManager()),
            ],
        ),
    ]
