# Generated by Django 3.1.12 on 2021-07-04 16:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import poolink_backend.bases.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_prefer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('path', models.TextField(help_text='알게된 경로', verbose_name='알게된 경로')),
            ],
            options={
                'abstract': False,
            },
            bases=(poolink_backend.bases.models.UpdateMixin, models.Model),
        ),
    ]
