# Generated by Django 3.1.12 on 2021-07-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
    ]
