# Generated by Django 3.1.12 on 2021-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210808_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agreed_to_terms',
            field=models.BooleanField(default=False, help_text='이용약관에 동의하였는지 여부를 나타냅니다.', verbose_name='약관동의여부'),
        ),
    ]
