# Generated by Django 3.1.12 on 2022-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('users', '0012_user_is_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_tags',
            field=models.ManyToManyField(help_text='유저의 선호 태그들입니다.', null=True, related_name='preferred_tag', to='hashtag.Hashtag'),
        ),
    ]
