# Generated by Django 3.1.12 on 2022-03-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import poolink_backend.bases.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_preferred_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('feedback', models.TextField(help_text='피드백', verbose_name='피드백')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='피드백 작성자')),
            ],
            options={
                'abstract': False,
            },
            bases=(poolink_backend.bases.models.UpdateMixin, models.Model),
        ),
    ]
