# Generated by Django 3.1.12 on 2022-03-10 06:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import poolink_backend.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('name', models.CharField(help_text='태그 이름입니다.', max_length=100, verbose_name='태그이름')),
            ],
            options={
                'verbose_name': '해시태그',
                'verbose_name_plural': '해시태그',
            },
            bases=(poolink_backend.bases.models.UpdateMixin, models.Model),
        ),
    ]
