# Generated by Django 3.1.12 on 2021-06-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름없는 보드', help_text='보드의 이름입니다', max_length=255, verbose_name='보드 이름')),
                ('image', models.ImageField(help_text='유저가 설정한 보드 이미지입니다.', null=True, upload_to='', verbose_name='보드 이미지')),
                ('bio', models.TextField(help_text='보드에 대한 설명입니다', null=True, verbose_name='보드 설명')),
                ('charge', models.BooleanField(default=False, help_text='유료 보드인지를 나타냅니다. MVP 단계에서 사용되지 않습니다.', verbose_name='유료보드 설정 여부')),
                ('like_count', models.IntegerField(help_text='보드의 좋아요 수를 나타냅니다.', verbose_name='좋아요 수')),
                ('scrap_count', models.IntegerField(help_text='보드가 스크랩 된 수를 나타냅니다.', verbose_name='스크랩 수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='보드 소유자')),
            ],
            options={
                'verbose_name': '보드',
                'verbose_name_plural': '보드',
            },
        ),
    ]
