# Generated by Django 3.1.12 on 2021-06-27 06:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부'),
        ),
        migrations.AddField(
            model_name='board',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='board',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
