# Generated by Django 3.1.12 on 2021-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('board', '0003_auto_20210704_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ManyToManyField(related_name='board_category', to='category.Category'),
        ),
    ]
