# Generated by Django 3.1.12 on 2021-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210704_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, help_text='유저가 설정한 보드 이미지입니다.', null=True, upload_to='media', verbose_name='보드 이미지'),
        ),
    ]
