# Generated by Django 3.1.12 on 2021-07-05 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_category_color'),
        ('board', '0005_auto_20210705_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ManyToManyField(null=True, related_name='board_category', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='like',
            field=models.ManyToManyField(null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='scrap',
            field=models.ManyToManyField(null=True, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
