# Generated by Django 3.1.12 on 2021-08-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210721_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bio',
            field=models.TextField(blank=True, help_text='보드에 대한 설명입니다', null=True, verbose_name='보드 설명'),
        ),
    ]
