# Generated by Django 3.1.12 on 2021-09-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210807_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='like',
        ),
    ]
