# Generated by Django 3.1.12 on 2022-01-14 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0009_remove_board_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='invited_users',
            field=models.ManyToManyField(null=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
