# Generated by Django 3.1.12 on 2022-01-14 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210808_0619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0010_board_invited_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='board_category', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='scrap',
            field=models.ManyToManyField(blank=True, null=True, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
