# Generated by Django 3.1.12 on 2022-01-24 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_auto_20220114_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='invited_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='invited_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
