# Generated by Django 3.1.12 on 2022-02-04 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210808_0619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0012_auto_20220124_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_bookmarked',
            field=models.BooleanField(default=False, help_text='보드의 즐겨찾기 등록 여부를 나타냅니다.', verbose_name='즐겨찾기'),
        ),
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='보드의 카테고리들입니다.', null=True, related_name='board_category', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='board',
            name='invited_users',
            field=models.ManyToManyField(blank=True, help_text='보드에 초대된 유저들입니다.', null=True, related_name='invited_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='scrap',
            field=models.ManyToManyField(blank=True, help_text='보드를 스크랩한 유저들입니다.', null=True, related_name='scrap', to=settings.AUTH_USER_MODEL),
        ),
    ]
