# Generated by Django 3.1.12 on 2022-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20220204_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='emoji',
            field=models.CharField(help_text='보드마다 설정되는 이모티콘입니다.', max_length=10, null=True, verbose_name='보드 이모티콘'),
        ),
    ]
