# Generated by Django 3.1.12 on 2022-02-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_board_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='searchable',
            field=models.BooleanField(default=True, help_text='보드의 탐색페이지 공개 여부입니다.', verbose_name='탐색 가능 여부'),
        ),
    ]
