# Generated by Django 3.1.12 on 2022-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        ('board', '0015_board_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(help_text='보드의 해시태그입니다.', null=True, related_name='tagged_boards', to='hashtag.Hashtag'),
        ),
    ]
