# Generated by Django 3.1.12 on 2021-07-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(help_text='카테고리의 색상코드입니다.', max_length=20, null=True, verbose_name='카테고리 색상'),
        ),
    ]
