# Generated by Django 3.1.12 on 2021-07-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='카테고리의 색상코드입니다.', max_length=20, null=True, verbose_name='카테고리 색상'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='카테고리의 이미지입니다.', null=True, upload_to='media', verbose_name='카테고리 이미지'),
        ),
    ]
