# Generated by Django 3.1.12 on 2022-03-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, '초대됨'), (1, '수락'), (2, '거절')], default=0),
        ),
    ]
