# Generated by Django 3.1.12 on 2021-07-04 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import poolink_backend.bases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0005_auto_20210705_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='활성화 여부')),
                ('label', models.CharField(help_text='링크의 라벨입니다', max_length=255, verbose_name='링크 라벨링')),
                ('url', models.URLField(help_text='링크의 url 주소입니다.', verbose_name='링크 주소')),
                ('alarm', models.DateTimeField()),
                ('show', models.BooleanField(default=True, help_text='링크의 공개 여부를 나타냅니다.', verbose_name='링크 공개 여부')),
                ('favicon', models.URLField(help_text='링크의 파비콘(favicon)입니다.', null=True, verbose_name='링크 파비콘')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='board.board', verbose_name='상위 보드')),
            ],
            options={
                'verbose_name': '링크',
                'verbose_name_plural': '링크',
            },
            bases=(poolink_backend.bases.models.UpdateMixin, models.Model),
        ),
    ]
