# Generated by Django 3.1.12 on 2021-07-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='alarm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='favicon',
            field=models.URLField(blank=True, help_text='링크의 파비콘(favicon)입니다.', null=True, verbose_name='링크 파비콘'),
        ),
    ]
