# Generated by Django 3.1.12 on 2021-07-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20210705_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-id'], 'verbose_name': '링크', 'verbose_name_plural': '링크'},
        ),
        migrations.AddField(
            model_name='link',
            name='meta_image',
            field=models.URLField(blank=True, help_text='링크의 미리보기 이미지입니다.', null=True, verbose_name='링크 미리보기 이미지'),
        ),
    ]
