# Generated by Django 3.1.12 on 2021-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20210721_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='favicon',
            field=models.TextField(blank=True, help_text='링크의 파비콘(favicon)입니다.', max_length=1000, null=True, verbose_name='링크 파비콘'),
        ),
        migrations.AlterField(
            model_name='link',
            name='meta_image',
            field=models.TextField(blank=True, help_text='링크의 미리보기 이미지입니다.', max_length=1000, null=True, verbose_name='링크 미리보기 이미지'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(help_text='링크의 url 주소입니다.', verbose_name='링크 주소'),
        ),
    ]
