# Generated by Django 3.1.12 on 2021-08-12 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_auto_20210813_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(
                help_text='링크의 url 주소입니다.', validators=[django.core.validators.URLValidator()], verbose_name='링크 주소'),
        ),
    ]
