# Generated by Django 3.1.12 on 2021-09-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_auto_20210813_0204'),
        ('link', '0005_auto_20210813_0213'),
        ('link', '0004_auto_20210813_0146'),
    ]

    operations = [
    ]
