# Generated by Django 3.1.12 on 2022-02-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_merge_20210902_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='memo',
            field=models.TextField(blank=True, help_text='링크에 대한 메모입니다.', null=True, verbose_name='링크 메모'),
        ),
    ]
